[versions]
# Libraries
kotlin = "2.1.10"
kotest = "5.9.1"

# Plugins
spotless = "7.0.2"
ktlint = "1.5.0"

[libraries]
kotest = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotestAssertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotestRunnerJunit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
ktlint-cli = { id = "com.pinterest.ktlint:ktlint-cli", version.ref = "ktlint" }